server:
  port: 8001
spring:
  application:
    name: exam-user-provider-8001
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myproject?serverTimezone=UTC
    password: root
    username: root
    name: defaultDataSource
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    port: 6379
    host: 192.168.147.130
    timeout: 10s
    jedis:
      pool:
        max-idle: 50        # 最大空闲连接数
        min-idle: 10        # 最小空闲连接数
        max-wait:  -1s        # 等待可用连接的最大时间，负数为不限制
        max-active: -1        # 最大活跃连接数，负数为不限制
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版
    register-with-eureka: true
    fetch-registry: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.exam.entity
  type-enums-package: com.exam.enums #枚举包扫描
#  global-config:
#    db-config:
#      logic-not-delete-value: 0
#      logic-delete-value: 1
