server:
  port: 9001
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
ribbon:
  ReadTimeout: 5000  #openfeign 默认等待时长 1s
  ConnectTimeout: 5000

spring:
  application:
    name: exam-user-consumer-9001
  redis:
    port: 6379
    host: 192.168.147.130
    timeout: 10s
  jedis:
    pool:
      max-idle: 50        # 最大空闲连接数
      min-idle: 10        # 最小空闲连接数
      max-wait:  -1s        # 等待可用连接的最大时间，负数为不限制
      max-active: -1        # 最大活跃连接数，负数为不限制

# Actuator Web 访问端口
management:
  server:
    port: 8081
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

#服务降级的开关
feign:
  hystrix:
    enabled: true