server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002.com
  client:
    register-with-eureka: true #不向注册中心注册自己
    fetch-registry: false #表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      #设置与Eureka server 交互的地址查询服务与注册服务都需要依赖这个地址
      defaultZone: http://eureka7001.com:7001/eureka
  #server:
    #eviction-interval-timer-in-ms: 60000 #保证不可用的微服务的时间
    #enable-self-preservation: false  #关闭eureka的自我保护机制,保证不可用的微服务能够被及时剔除